# Configuration for JavaScript/TypeScript projects
# This example shows setup for fixing Node.js applications

# Repository settings
repository_path: "/path/to/javascript/project"
problem_description: "Fix the memory leak in the Express.js application causing high memory usage"
target_files:
  - "src/server.js"
  - "src/middleware/auth.js"
  - "src/routes/api.js"
exclude_patterns:
  - "node_modules"
  - "*.log"
  - ".git"
  - "dist/"
  - "build/"
  - "coverage/"

# Number of patch candidates
num_patch_candidates: 10

# JavaScript-focused agents
agents:
  - agent_id: "javascript_expert"
    model_name: "claude-sonnet-4-5-20250929"
    temperature: 0.7
    max_tokens: 2048
    system_prompt: "You are an expert JavaScript/Node.js developer focused on fixing memory leaks and performance issues."
    specialized_role: "general"

  - agent_id: "nodejs_specialist"
    model_name: "claude-sonnet-4-5-20250929"
    temperature: 0.6
    max_tokens: 2048
    system_prompt: "You are a Node.js specialist focused on server-side optimization and memory management."
    specialized_role: "performance"

  - agent_id: "express_expert"
    model_name: "claude-sonnet-4-5-20250929"
    temperature: 0.5
    max_tokens: 2048
    system_prompt: "You are an Express.js expert focused on middleware optimization and request handling."
    specialized_role: "framework"

# Vector database configuration
vectordb:
  provider: "chromadb"
  collection_name: "js_code_embeddings"
  persist_directory: "./data/vectordb_js"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  chunk_size: 600
  chunk_overlap: 60

# OpenCode configuration
opencode:
  enabled: true
  max_parallel_agents: 3
  timeout_seconds: 300

# Evaluation configuration
evaluation:
  method: "ab_testing"
  model_name: "claude-sonnet-4-5-20250929"
  temperature: 0.1
  max_tokens: 2048
  min_comparisons_per_patch: 3
  confidence_threshold: 0.75

# JavaScript testing configuration
testing:
  test_command: "npm test"
  test_timeout_seconds: 300
  pre_test_commands:
    - "npm install"
    - "npm run build"
  post_test_commands:
    - "npm run lint"
  fail_on_regression: true

# Logging configuration
logging:
  level: "INFO"
  output_dir: "./experiments/javascript"
  log_file: "js_experiment.log"
  save_patches: true
  save_evaluations: true
  save_test_results: true
  console_output: true